services:
  frontend:
    container_name: frontend
    volumes:
    - ./frontend:/app:cached
    - node_modules_frontend:/app/node_modules
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    environment:
      - RTE=${RTE}
    env_file:
      - ./frontend/.env.${RTE}
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - external-network
  backend:
    container_name: backend
    volumes:
    - ./backend:/app:cached
    - node_modules_backend:/app/node_modules
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    environment:
      - RTE=${RTE}
    env_file:
      - ./backend/.env.${RTE}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - internal-network
      - external-network
  db:
    container_name: db
    image: postgres:17
    restart: unless-stopped
    env_file:
      - ./backend/.env.${RTE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./nginx.${RTE}.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - internal-network
      - external-network

networks:
  internal-network:
    driver: bridge
  external-network:
    driver: bridge


volumes:
  node_modules_frontend:
  node_modules_backend:
  pgdata:
