services:
  frontend:
    container_name: frontend
    volumes:
    - ./frontend:/app:cached
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - RTE=${RTE}
    env_file:
      - ./frontend/.env.${RTE}
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - external-network
  backend:
    container_name: backend
    volumes:
    - ./backend:/app:cached
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "4000:4000"
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - RTE=${RTE}
    env_file:
      - ./backend/.env.${RTE}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - internal-network
      - external-network
  db:
    container_name: db
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  internal-network:
    driver: bridge
  external-network:
    driver: bridge

volumes:
  pgdata: {}
