name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Pull, Deploy, Prune via SSH
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e
            echo "== Navigating to app folder =="
            cd /root/bachelor_exam
            echo "== Stashing and pulling latest code on master branch =="
            git stash
            git fetch origin
            git checkout master
            git pull origin master
            echo "== Shutting down current containers =="
            RTE=prod docker compose down
            echo "== Building and starting containers =="
            RTE=prod docker compose up -d --build
            echo "== Pruning unused Docker resources =="
            docker system prune -af
            docker volume prune -f
            echo "== Listing running containers =="
            docker ps -a
          EOF
